# Numpy training and examples

### Author: Samyakh Tukra (2017/18)

#### The following shows the basics of creating arrays and the formatting of arrays:

Remember the following: 
• Numpy is the fundamental package for working with N-dimensional
array objects (vector, matrix, tensor, …)

• But what is the difference between vector, matrix and a tensor, well the following image explains it:
well a vector is a 1d tensor, i.e. a column of numbers. A Matrix is a 2d tensor i.e. a 3 (rows) by 3(columns) square matrix of numbers. A Tensor is nd (i.e. 3d and above) its like a cube/3d rectangle.

In [1]:
## Basic Numpy datatypes

''' So first import numpy and rename it as np'''
import numpy as np

In [38]:
# to get the version of numpy we are using:
print(np.__version__)


1.13.3


In [19]:
#very similar to lists:

# to create an array simply use the following function: np.array()

a= np.array([1,2,3]) # notice how () are used to start the functions, but
# the array is defined by a square brackets and separated by commas
print a

u= np.array ([4,5,6]) # so each element in [] defines the row i.e. x.... hence
# this matrix is a 1 by 3 matrix

# to make a bigger matrix we simply add more rows.... i.e.
x= np.array([[1,2,3],[4,5,6],[7,8,9]]) # notice we have one big square brackets that engulfs the individual
'''small square brackets in the function... this is to define the matrix as a whole
 the individual square brackets defines the individual rows i.e. x's
 Hence, each of the [1,2,3] is a row... in the function'''

print u
print x

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# We can also turn our lists into values i.e.
my_list= [3,6,8,0,19,10]
# now convertting it into a numpy array uses the same function
my_array= np.array(my_list)
my_array

array([ 3,  6,  8,  0, 19, 10])

In [12]:
# to multiply the array by a scalar 10 simply multiply!
my_array*10


array([ 30,  60,  80,   0, 190, 100])

In [13]:
# to see what type of array we have, simply use the type() function
print(type(my_list))


<type 'list'>


In [14]:
print(type(my_array))


<type 'numpy.ndarray'>


In [23]:
# In addition to type we can also get the shape, i.e. is the matrix 1by 3 or 2by3
# to do this, we simply use the shape function array_name.shape

g= np.array([[4,5,6,7,8],[10,11,12,13,14]])

print(np.shape(x)) # this is a 3by3 matrix
print(np.shape(g)) # this is a 2 by 5 matrix

(3L, 3L)
(2L, 5L)


#### The Following are some functions built into numpy that you must know:

In [27]:
### Other functions you should know:
np.arange(7) # the arange() function (pronounces a-range) it creates an array of a
# range of integers. This range starts with 0 up until but not including the final
# parameter. i.e. evenly spaced values in a given interval
''' the function parameters are as follows: np.arange([start],[stop],[dtype])
so start value by default is 0, hence no need to state it unless you want the
matrix to begin at 1 or 3 or any number of choice, stop is the end of the interval
i.e. the interval will not include this number. finally dtype is the data type 
you want i.e. float32 or int16 another parameter that you can use after stop is
step... which defines the spacing between the values'''
print np.arange(7)
print np.arange(1,5,0.5) # dtype is automatically crerated based on your other
# inputs



[0 1 2 3 4 5 6]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5]


In [29]:
len(np.arange(1,5,0.2)) # len helps us find the length i.e. size of the array
# i.e. how many elements there are

# numpy also has a function that let's me find the total no. of elements its
# called, size()
i= np.arange(1,5,0.2)
i.size


20

In [34]:
### Another function to create array that are linearly spaced is using
# linspace() which creates a group of integers linearly spaced (evenly)
'''np.linspace(start,stop,num,endpoint=True,retstep=True)
so start and stop are the same as arange our value boundaries, num is the number
of samples you want to generates (default is 50), endpoint is a boolean,
so if True (default) the stop is the value of the last sample, retstep
which is a boolean if set to True allows you to see the step size (increments)'''
# As opposed ot the arange() the last number is included in the array!
np.linspace(5,15,9) # 5 to 15 (including last num) numbers in 9 total elements

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [35]:
np.linspace(1,10)

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [36]:
np.linspace(1,10,10) # will generate 10 samples! equally spaced

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [37]:
np.linspace(1,10,10,retstep=True) # the last component should be 1.0 i.e.
# the elements will go up in increments of 1.0

(array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]), 1.0)

In [39]:
### zeros() function will essentially create an array filled with zeros.
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [42]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [43]:
np.zeros((10,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [44]:
# Similarly same can be done with ones using the ones() function:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [3]:
''' Now create a 3 dimensional array, rememebr when I said each [] entry is a
row... i.e. it is a one dimension matrix, the external box [] makes it a 2d 
matrix constituted of 1d parts. Well to get it in 3d we simply add in a 
3rd parameter'''

np.zeros((5,4,3))# first component 5 says we have 5 2d arrays, 2nd component
# says we have 4 groups of matrices and the last component says we have 3 columns
# Hence why there are 3 outer brackets.

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [4]:
f= np.zeros((5,4,3))
print f.shape
print np.size(f)

(5L, 4L, 3L)
60


In [5]:
# You can also get the data type of the actual array
f.dtype
# you can have different dtypes... even complex matrices by setting
# dtype = complex

dtype('float64')

In [6]:
j=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print j

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
j[1:2,2:3]


array([[7]])

In [8]:
print(j[1:2,2:3])


[[7]]


In [9]:
j[1][2]

7

In [10]:
j[1,2]

7

In [11]:
j[:2,1:3]# remember it never includes the last row/column only the start number
# and the last-1 number.

array([[2, 3],
       [6, 7]])

In [12]:
j[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

In [13]:
j[1:4,1:4]


array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [5]:
b= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
b[0]

array([1, 2, 3, 4])

In [7]:
b[0:1]

array([[1, 2, 3, 4]])

In [8]:
b[0,0]

1

In [9]:
b[0:2,0]


array([1, 5])

In [10]:
b[0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
b[-3] # simply taking out the row and counting from the bottom

array([5, 6, 7, 8])

In [12]:
b.size

16

In [13]:
b.shape

(4, 4)

In [14]:
b.dtype

dtype('int32')

In [17]:
new_array=np.arange(35)
new_array.shape=(7,5)
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

# Broadcasting Arrays:

In [2]:
# now I am going to consider slicing a tensor:
# this is simply creating 3d arrays:
TD_array= np.arange(70)
TD_array.shape= (2,7,5) # 7 rows, 5 columns and 2 layers in (2*7=14 *5 = 70)
TD_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [3]:
TD_array.shape

(2, 7, 5)

In [5]:
# The following will give the no of dimensions using the ndim function:
print(TD_array.ndim) # result  = 3 i.e. 3 dimensions
print(TD_array.size) # tells me the size.... i.e. the no of elements should be 70
print(TD_array.dtype) # gives me the data type for each element... i.e. int32: 32 bit integers


3
70
int32


In [19]:
TD_array[1] # this will obtain a single layer of the 2 dimensional tensor in
# the case below it obtains the second layer since the first layer begins with 0

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [20]:
TD_array[1,3] # this gives us the second layer (i.e. layer indexed 1) and the 4th
# row of that layer
# thus slicing tensors= [layer, row, column]


array([50, 51, 52, 53, 54])

In [21]:
TD_array[1,3,2]# will give me a single element


52

In [24]:
# to change the values of a row or element simply refernce that part using the same
#slicing methods and then assign a different value: i.e.
TD_array[1,3,2] = 111
TD_array
# assiging the above element 52 a different value of 111

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34]],

       [[ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51, 111,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69]]])

In [26]:
TD_array[1,3]=[111,112,113,114,115]
TD_array

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34]],

       [[ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [111, 112, 113, 114, 115],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69]]])

### So remember, to slice an array you use square brakets [ ] and to create an array you use simple brackets ( ) i.e. np.array([1,2,3],[1,2,3])

In [5]:
x= np.array([[1,2,3],[4,5,6],[7,8,9],[9,1,4]])
print('this is the x array {}'.format(x))
x[:2,:1]

this is the x array [[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 1 4]]


array([[1],
       [4]])

In [6]:
u= np.arange(30)
u.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# Boolean Mask Arrays

### This is essentially to do with indexing an array using some logic operators

In [7]:
a= np.arange(10)
a[(a>2)&(a<7)] # getting all values from the a vector that are bigger than 2 AND less than seven.


array([3, 4, 5, 6])

In [9]:
a[~(a>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
np.random.rand(4,5)

array([[0.89558154, 0.34275186, 0.6315173 , 0.39276864, 0.77649587],
       [0.81201938, 0.78151105, 0.21028946, 0.97544788, 0.91719646],
       [0.61041654, 0.15365853, 0.88206642, 0.45047208, 0.61200536],
       [0.79725858, 0.88623563, 0.24606758, 0.01385505, 0.35204651]])

In [8]:
x= np.random.rand(3,2)
y= np.random.rand(2,3)


In [10]:
%time np.dot(x,y)


Wall time: 0 ns


array([[0.56592587, 0.36247042, 0.36107794],
       [0.47644484, 0.35639552, 0.31700806],
       [0.71528397, 0.57191416, 0.4852902 ]])

In [11]:
z=np.dot(x,y)
np.transpose(z)


array([[0.56592587, 0.47644484, 0.71528397],
       [0.36247042, 0.35639552, 0.57191416],
       [0.36107794, 0.31700806, 0.4852902 ]])